### PR TITLE
startGame now has intelligence levels.

### PR DESCRIPTION
**Pull request by StaticNomad**
To run startgame, we should now pass in intelligence levels. Passing in
0 will run with random moves; 1 will use the bloodhunter technique, and
2 and 3 will be varying levels of IDS depth limits, which will search
out at a certain move length, then use bloodhunter as default.

### CODE REVIEW

**Comment by StaticNomad** [comment]
This fulfills the requirements for #22. I've begun drilling into the intelligentMove function but I'm having a lot of troubles with debugging. What I've figured out thus far is this:

When iterating over the available actions in intelligentMove, depthLimitedSearch, and takeActionShortestDistance AFTER going through the IDS implementation portion of intelligentMove, the actions are opposite of what we'd expect. For example, when a Ghost should have available actions as Down and Right, they currently have Up and Left available.

I'll have some more time tomorrow night to drill in to this.

**Comment by SteelHeart13** [comment]
Question would you like me to wait to do the pull request for the board update until this one goes through or vice versa?

**Comment by StaticNomad** [comment]
@SteelHeart13 go ahead and make your pull request; I'll make sure my stuff doesn't conflict

**Comment by StaticNomad** [comment]
No one merge this yet. It needs work. A lot of conflicting problems with the new board object.

**Comment by StaticNomad** [comment]
@SteelHeart13 can you check out this branch and run through the game, at least until the third step? Some of the stuff in takeActions and Actions in the ghosts is still not working for boards.

**Comment by jurentie** [comment]
Wow! Good Job!

**Pull request merged**
